<?php

/**
 * @file
 * Drush integration for the relation module.
 */

/**
 * Implements hook_drush_command().
 */
function relation_drush_command() {
  $items['relation-generate'] = array(
    'description' => dt('Generates relations.'),
    'arguments' => array(
      'number_relations' => dt('The number of relations to generate.'),
    ),
    'options' => array(
      'kill' => 'Delete all relations before generating new ones.',
      'types' => 'A comma delimited list of relation types to create.',
    ),
    'aliases' => array('genrel'),
  );
  return $items;
}

/**
 * Drush callback to generate relations.
 *
 * @param $number_relations
 *   Number of entities to generate of each entity_type.
 */
function drush_relation_generate($number_relations) {
  $types = drush_get_option('types');
  $types = $types ? explode(',', $types) : array();
  $kill = drush_get_option('kill');
  relation_generate_relations($number_relations, $types, $kill);
}

/**
 * Sends message to drush log, if enabled.
 *
 * @param $message
 *   Text of message.
 */
function relation_generate_message($message) {
  if (function_exists('drush_log')) {
    drush_log($message, 'ok');
  }
  else {
    drupal_set_message($message);
  }
}

/**
 * Generates pseudorandom relations. Appropriate entities must already exist.
 *
 * @param $number_relations
 *   Number of entities to generate of each entity_type.
 * @param $types
 *   Array of relation_type to generate and delete relations. Set to NULL to
 *   generate and delete all.
 * @param $kill
 *   Whether to delete all existing relations before creating new ones.
 *
 * @return
 *   Array of rids of the generated relations.
 */
function relation_generate_relations($number_relations = 10, $relation_types = array(), $kill = FALSE) {
  $relation_types = entity_load_multiple('relation_type', $relation_types);
  if ($kill) {
    foreach ($relation_types as $relation_type) {
      $relation_ids = entity_query('relation')
        ->condition('relation_type', $relation_type->id())
        ->execute();
      entity_delete_multiple('relation', $relation_ids);
      relation_generate_message(t('Deleted all @type relations.', array('@type' => $relation_type->label())));
    }
  }

  $new_rids = array();
  foreach ($relation_types as $relation_type) {
    $available_types = array();
    foreach ($relation_type->source_bundles as $bundle_key) {
      list($entity_type, $bundle) = explode(':', $bundle_key, 2);
      $available_types['source'][$entity_type][] = $bundle;
    }
    foreach ($relation_type->target_bundles as $bundle_key) {
      list($entity_type, $bundle) = explode(':', $bundle_key, 2);
      $available_types['target'][$entity_type][] = $bundle;
    }
    $arity = rand($relation_type->min_arity, $relation_type->min_arity);

    for ($i = $number_relations; $i > 0; $i--) { // start new relation
      $entity_keys = array();
      for ($r_index = 0; $r_index < $arity; $r_index++) {
        $direction = ($relation_type->directional && $r_index > 0) ? 'target' : 'source';
        $entity_type = array_rand($available_types[$direction]);
        $entity_info = entity_get_info($entity_type);
        $bundles = entity_get_bundles($entity_type);
        $query = entity_query($entity_type);

        if (!in_array('*', $available_types[$direction][$entity_type])) {
          // Entities with a single bundle don't support EFQ bundle condition.
          if (count($bundles) > 1 && isset($entity_info['entity_keys']['bundle'])) {
            $query->condition($entity_info['entity_keys']['bundle'], $available_types[$direction][$entity_type], 'IN');
          }
        }

        if ($results = $query->execute()) {
          $key = array_rand($results);
          $entity_keys[] = array(
            'entity_type' => $entity_type,
            'entity_id'   => $results[$key],
            'r_index'     => $r_index,
          );
        }
      }
      $relation = relation_insert($relation_type->id(), $entity_keys);
      $new_rids[] = $relation->id();
      relation_generate_message(t('Generated @number_relations @type relations.', array('@number_relations' => $number_relations, '@type' => $relation_type->id())), 'ok');
    }
  }
  return $new_rids;
}
