<?php

/**
 * @file
 * Describes relations between entities.
 */

/**
 * Implements hook_entity_info().
 */
function relation_entity_info() {
  $entities['relation'] = array(
    'label' => t('Relation'),
    'base table' => 'relation',
    'fieldable' => FALSE,
    'controller class' => 'RelationEntityController',
    'entity keys' => array(
      'id' => 'relation_id',
      'bundle' => 'predicate',
    ),
    'bundle keys' => array(
      'bundle' => 'predicate',
    ),
    'bundles' => array(
      // Describe Drupal's built-in relations.
      'creator' => array(
        'label' => t('Author'),
      ),
    ),
    'view modes' => array(),
  );
  return $entities;
}

/**
 * implement hook_permission().
 */
function relation_permission() {
  return array(
    'administer relation' => array(
      'title' => t('Administer Relations'),
      'description' => t('Perform administration tasks for relations.'),
    ),
  );
}

/**
 * implement hook_menu().
 */
function relation_menu() {
  $items['relation/%relation'] = array(
    'access arguments' => array('access content'),
    'page callback' => 'relation_page',
    'page arguments' => array(1),
  );
  // will need to be moved, when relation bundles (predicates) are implemented.
  $items['admin/structure/relation'] = array(
    'title' => 'Relation',
    'access arguments' => array('access content'),
    'page callback' => 'relation_config',
    'type' => MENU_LOCAL_TASK,
    'page arguments' => array(1),
  );
  return $items;
}

/**
 * relation settings page, proof of concept, most will need to be moved
 * to relation bundle settings page.
 */
function relation_config() {
  $bundles = array();
  foreach (module_invoke_all('entity_info') as $entity_type => $entity) {
    if (isset($entity['bundles'])) {
      foreach ($entity['bundles'] as $bundle_id => $bundle) {
        $bundles[$entity_type . '_' . $bundle_id] = $bundle['label'] . ' (' . $entity['label'] . ')';
      }
    }
  }
  $form['predicate'] = array(
    '#type'         => 'textfield',
    '#title'        => 'Predicate',
    '#description'  => 'Title of the relation type',
  );
  $form['available_bundles'] = array(
    '#type'         => 'select',
    '#title'        => 'Available bundles',
    '#options'      => $bundles,
    '#size'         => min(12, count($bundles)),
    '#multiple'     => TRUE,
    '#description'  => 'Bundles that are not selected will not be available as end points for relations. Ctrl+click to select multiple.',
  );
  $form['directional'] = array(
    '#type'         => 'checkbox',
    '#title'        => 'Directional?',
    '#options'      => FALSE,
  );
  return $form;
}

function relation_load($relation_id) {
  return reset(entity_load('relation', array($relation_id)));
}

function relation_page($relation) {
  $left_entity = reset(entity_load($relation->left_entity_type, array($relation->left_entity_id)));
  $left_uri = entity_uri($relation->left_entity_type, $left_entity);
  $right_entity = reset(entity_load($relation->right_entity_type, array($relation->right_entity_id)));
  $right_uri = entity_uri($relation->right_entity_type, $right_entity);
  $build['link_list'] = array(
    '#theme' => 'item_list',
    '#items' => array(
      l(entity_label($relation->left_entity_type, $left_entity), $left_uri['path'], $left_uri['options']),
      l(entity_label($relation->right_entity_type, $right_entity), $right_uri['path'], $right_uri['options']),
    ),
  );
  return $build;
}

/**
 * Controller class for entity relations.
 *
 * This extends the DrupalDefaultEntityController class. The buildQuery method
 * is overriden to add the self join and to exclude rows where the left and
 * right entities are identical.
 */
class RelationEntityController extends DrupalDefaultEntityController {
  protected function buildQuery($ids, $conditions = array(), $revision_id = FALSE) {
    $query = parent::buildQuery($ids, $conditions, $revision_id);
    _relation_entity_query_helper($query);
    return $query;
  }
}

function _relation_entity_query_helper($query) {
  $query->innerJoin('relation_data', 'l', 'base.relation_id = l.relation_id');
  $query->innerJoin('relation_data', 'r', 'base.relation_id = r.relation_id AND NOT (l.entity_type = r.entity_type AND l.entity_id = r.entity_id)');
  $query->addField('base', 'relation_id');
  $query->addField('base', 'predicate');
  $query->addField('l', 'entity_type', 'left_entity_type');
  $query->addField('l', 'entity_id', 'left_entity_id');
  $query->addField('r', 'entity_type', 'right_entity_type');
  $query->addField('r', 'entity_id', 'right_entity_id');
}

/**
 * Interface for relation handlers.
 */
interface RelationInterface {
  // bangpound
  public function getRelated($entity, $type);

  // becw
  function init($left, $right); // sets types
  function set_left($entity_ids = array()); // sets left objects
  function set_right($entity_ids = array()); // sets right objects
  function get_left(); // returns left
  function get_right(); // returns right
}

/**
 * Handler class for entity relations.
 */
class RelationHandler implements RelationInterface {

  function __construct() {
  }

  /**
   * Entity is a fully loaded entity (node, user, term, etc.)
   * Type is the predicate.
   */
  public function getRelated($entity, $type) {
    return NULL;
  }

  function init($left, $right) {
  }

  function set_left($entity_ids = array()) {
  }

  function set_right($entity_ids = array()) {
  }

  function get_left() {
  }

  function get_right() {
  }
}
/**
 * Create a relation.
 *
 * @param $entity_keys
 *   A list of (entity_type, entity_id) pairs.
 * @return
 *   The new relation id.
 */
function relation_create($entity_keys) {
  $relation_id = db_insert('relation')->useDefaults(array('relation_id'))->execute();
  $query = db_insert('relation_data')
    ->fields(array('relation_id', 'entity_type', 'entity_id'));
  foreach ($entity_keys as $entity_key) {
    $query->values(array($relation_id, $entity_key[0], $entity_key[1]));
  }
  $query->execute();
  return $relation_id;
}

/**
 * Implements hook_block_info().
 */
function relation_block_info() {
  return array(
    'dropzone' => array(
      'info' => t('Relation block'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function relation_block_view() {
  $form = drupal_get_form('relation_dropzone');
  if (isset($form['entity_key'])) {
    return array(
      'subject' => t('Pick an entity'),
      'content' => $form,
    );
  }
  return array();
}

/**
 * The dropzone form.
 */
function relation_dropzone($form) {
  $options = array();
  foreach (drupal_static('relation_entities', array()) as $entity_type => $entities) {
    foreach ($entities as $entity_id => $entity) {
      $options["$entity_type:$entity_id"] = "$entity_type: " . entity_label($entity_type, $entity);
    }
  }
  if ($options) {
    $form['entity_key'] = array(
      '#type'         => 'select',
      '#options'      => $options,
    );
    if (count($options) > 1) {
      $form['entity_key']['#empty_value'] = '';
      $form['entity_key']['#empty_option'] = t('Select an entity');
    }
    $form['pick'] = array(
      '#type' => 'submit',
      '#submit' => array('relation_dropzone_pick'),
      '#value' => t('Pick'),
    );
    if (!empty($_SESSION['stored_entity_keys'])) {
      $list = array();
      foreach ($_SESSION['stored_entity_keys'] as $entity_key) {
        // The structure is (entity_type, entity_id, entity label).
        $list[] = $entity_key[2];
      }
      $form['stored'] = array(
        '#theme' => 'item_list',
        '#items' => $list,
      );
      $form['save'] = array(
        '#type' => 'submit',
        '#value' => t('Create relation'),
        '#submit' => array('relation_dropzone_save'),
      );
      if (isset($_SESSION['stored_entity_keys'])) {
        $form['clear'] = array(
          '#type' => 'submit',
          '#value' => t('Clear'),
          '#submit' => array('relation_dropzone_clear'),
        );
      }
    }
  }
  return $form;
}

/**
 * Submit handler for the pick button.
 */
function relation_dropzone_pick($form, $form_state) {
  if ($entity_key = $form_state['values']['entity_key']) {
    // Here we get (entity_type, entity_id).
    $pick = explode(':', $entity_key);
    // Add the label for later display. #options is check_plain'd but we need
    // to do that ourselves.
    $pick[] = check_plain($form['entity_key']['#options'][$entity_key]);
    $_SESSION += array('stored_entity_keys' => array());
    $_SESSION['stored_entity_keys'][] = $pick;
  }
}

/**
 * Submit handler for the save button.
 */
function relation_dropzone_save($form, $form_state) {
  relation_dropzone_pick($form, $form_state);
  if (isset($_SESSION['stored_entity_keys'])) {
    relation_create($_SESSION['stored_entity_keys']);
    unset($_SESSION['stored_entity_keys']);
  }
}

/**
 * Submit handler for the clear button.
 */
function relation_dropzone_clear($form, $form_state) {
  unset($_SESSION['stored_entity_keys']);
}

/**
 * Implements hook_entity_load().
 */
function relation_entity_load($entities, $type) {
  $entities_store = &drupal_static('relation_entities', array());
  $enabled = &drupal_static(__FUNCTION__);
  // Recursion protection.
  if ($enabled === -1) {
    return;
  }
  if (!isset($enabled)) {
    $enabled = -1;
    drupal_theme_initialize();
    $block_info = _block_load_blocks();
    $enabled = FALSE;
    foreach ($block_info as $region => $blocks) {
      if (isset($blocks['relation_dropzone'])) {
        $enabled = TRUE;
        break;
      }
    }
  }
  if ($enabled) {
    $entities_store += array($type => array());
    $entities_store[$type] += $entities;
  }
}

