<?php

/**
 * Generate relations.
 *
 * @todo: move these functions to devel submodule.
 */
function relation_ui_generate_form($form, &$form_state) {
  $relation_types = entity_load_multiple('relation_type');

  if (empty($relation_types)) {
    $form['explanation']['#markup'] = t("Before you can generate relations, you need to define one or more !link.", array("!link" => l(t('relation types'), 'admin/structure/relation')));
    return $form;
  }
  foreach ($relation_types as $relation_type) {
    $options[$relation_type->id()] = array(
      'label' => $relation_type->label(),
    );
  }

  $header = array(
    'label' => t('Relation type'),
  );

  $form['relation_types'] = array(
    '#type' => 'tableselect',
    '#title' => t('Relation types'),
    '#description' => t('Select relation types to create relations from. If no types are selected, relations will be generated for all types.'),
    '#options' => $options,
    '#header' => $header,
  );
  $form['relation_kill'] = array(
    '#type' => 'checkbox',
    '#title' => t('Delete all relations in these relation types before generating new relations'),
  );

  $form['relation_number'] = array(
    '#type' => 'number',
    '#title' => t('How many relations would you like to generate of each type?'),
    '#default_value' => 10,
    '#size' => 10,
    '#min' => 0,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Generate'),
  );
  return $form;
}

function relation_ui_generate_form_submit($form, &$form_state) {
  $number = $form_state['values']['relation_number'];
  $relation_types = $form_state['values']['relation_types'];
  $kill = $form_state['values']['relation_kill'];
  include_once drupal_get_path('module', 'relation') . '/relation.drush.inc';
  $relation_types = array_keys(array_filter($relation_types));
  $relation_types = empty($relation_types) ? NULL : $relation_types;
  $rids = relation_generate_relations($number, $relation_types, $kill);
}

/**
 * Apply filters for relation administration filters based on session.
 *
 * @param $query
 *   A SelectQuery to which the filters should be applied.
 */
function relation_ui_build_filter_query($query) {
  if (!empty($_SESSION['relation_filters'])) {
    $query->join('field_data_endpoints', 'e', 'e.entity_id = r.rid');
    $query->distinct();
    foreach ($_SESSION['relation_filters'] as $filter => $values) {
      if (empty($values)) {
        continue;
      }
      switch ($filter) {
        case 'bundle':
          $query->condition('r.relation_type', array_keys($values), 'IN');
          break;
        case 'endpoints_entity_type':
          $query->condition('e.endpoints_entity_type', $values);
          break;
        case 'endpoints_entity_id':
          $query->condition('e.endpoints_entity_id', $values);
          break;
      }
    }
  }
}